### PR TITLE
temp fix: add "limit: 0" to most fetches to bypass Girder default

### LINKED ISSUE #150: Paging / Limits Defaults prevent seeing full list
**Steps to Reproduce**
1. Login to https://dashboard.stage.wholetale.org
2. Create a Tale
3. Navigate to Run > Files
4. Expand the dropdown and choose WT Catalog

**Expected Results**
You should see the full catalog listed

**Actual Results**
Notice the dataset results stop at "E"

**NOTES**

* This is true with all API endpoints where `limit` is not provided.
* Girder uses `/search` API for searching for Users

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
Some fetched listings on https://dashboard.stage.wholetale.org are incomplete. Girder has a non-zero default `limit` set for these HTTP requests, so we are not getting the full list sent back.

This default behavior will be helpful later, when we consider adding paging to these views, but for now it is problematic.

Fixes #150 as a temporary workaround 

Long-term, we should look into adding paging to the controls where we expect this many results to be listed

## Approach
Set a `limit: 0` on each of the relevant fetches.

I basically did a grep for the word "list", and added a limit for most of the resulting calls:
```bash
$ grep -ir 'service' src/app | grep -v html | grep -v scss | grep -vi listener | grep -i list | grep -v src/app/api
src/app/+user-settings/modals/connect-apikey-modal/connect-apikey-modal.component.ts:      this.accountService.accountListTargets({ provider: this.data.provider.name }).subscribe(targets => {
src/app/+user-settings/configure-accounts/configure-accounts.component.ts:    this.accountService.accountListAccounts(params).subscribe((accts: Array<Account>) => {
src/app/+tale-catalog/tale-catalog/modals/create-tale-modal/create-tale-modal.component.ts:    this.imageService.imageListImages(listImagesParams).subscribe(images => {
src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts:    this.tales$ = this.taleService.taleListTales(listTalesParams);
src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts:    this.instanceService.instanceListInstances(listInstancesParams).subscribe((instances: Array<Instance>) => {
src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts:    this.taleService.taleListTales(listTalesParams).subscribe((tales: Array<Tale>) => {
src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts:      this.tales$ = this.taleService.taleListTales(listTalesParams);
src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts:        this.tales$ = this.taleService.taleListTales({});
src/app/+run-tale/run-tale/modals/select-data-dialog/select-data-dialog.component.ts:    this.allDatasets = this.datasetService.datasetListDatasets({ myData: false, limit: 0 });
src/app/+run-tale/run-tale/modals/select-data-dialog/select-data-dialog.component.ts:    this.datasets = this.myDatasets = this.datasetService.datasetListDatasets({ myData: true, limit: 0 });
src/app/+run-tale/run-tale/modals/tale-workspaces-dialog/tale-workspaces-dialog.component.ts:    this.taleService.taleListTales(params).subscribe((tales: Array<Tale>) => {
src/app/+run-tale/run-tale/modals/publish-tale-dialog/publish-tale-dialog.component.ts:    this.repositoryService.repositoryListRepository().subscribe((repos: Array<Repository>) => {
src/app/+run-tale/run-tale/run-tale.component.ts:      this.instanceService.instanceListInstances(params).subscribe((instances: Array<Instance>) => {
src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.ts:    this.versionService.versionListVersions({ taleId: this.tale._id }).subscribe((versions: Array<Version>) => {
src/app/+run-tale/run-tale/tale-interact/tale-interact.component.ts:      this.instanceService.instanceListInstances(params)
src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.ts:    this.environments = this.imageService.imageListImages(params);
```

Note that "accounts" and "instances" have not had limits applied, as these likely won't scale over 100 entries. I can still go ahead and add them if we want some extra peace of mind there.

## How to Test
Prerequisites: lots and lots of test data (probably needs https://girder.stage.wholetale.org)

1. Checkout this branch locally, rebuild the dashboard
2. Login to the WholeTale Dashboard
3. View the Tale Catalog and/or Data Catalog
    * You should see all entries listed here (e.g. datasets results should include names that start with F-Z)

### CODE REVIEW

**Comment by Xarthisius** [comment]
I added a little something that fixes original issue reported by Craig in the move-to modal (missed limit=0 for folder/itemFind), plus filtering returning only folders writable by user.

**Review by Xarthisius — APPROVED** [review]

File: src/app/files/file-explorer/modals/move-to-dialog/move-to-dialog.component.ts [hunk 1]
```diff
@@ -162,14 +163,17 @@ export class MoveToDialogComponent implements OnInit {
 
     // Fetch folders in the current folder
     this.folderService
-      .folderFind({ parentId: this.currentFolderId, parentType: ParentType.Folder })
+      .folderFind({ parentId: this.currentFolderId, parentType: ParentType.Folder, limit: 0 })
```
Comment (craig-willis) [inline src/app/files/file-explorer/modals/move-to-dialog/move-to-dialog.component.ts:166]: How do you feel about changing the sort order to `updated` descending instead of the default `lowerName` (UUID in this case) ascending?

**Review by craig-willis — COMMENTED** [review]
FTR the issue is https://github.com/whole-tale/ngx-dashboard/issues/152

File: src/app/files/file-explorer/modals/move-to-dialog/move-to-dialog.component.ts (hunk 1 above)
Comment (Xarthisius) [reply src/app/files/file-explorer/modals/move-to-dialog/move-to-dialog.component.ts:166]: fine by me.

**Comment by craig-willis** [comment]
There's more to https://github.com/whole-tale/ngx-dashboard/issues/152 than just the limit, so I think we should address that separately. Otherwise, the limit stuff looks good to me.

**Review by craig-willis — APPROVED** [review]

**Review by craig-willis — APPROVED** [review]

**Comment by craig-willis** [comment]
This looks good to me. Noting that testing move to a subfolder in the workspace required https://github.com/whole-tale/virtual_resources/pull/11.

**Comment by bodom0015** [comment]
Appears to work as advertised :+1: I used Girder's Swagger UI page to quickly add many, many Tales to my dev instance, and they appear to all show up in the list 

Side-note: the user apparently still needs to manually refresh after the Move operation completes - is anyone else also seeing this as well? I thought we were manually triggering a refresh here, but I don't think we have new events any associated with File operations. We do have some with datasets, so it may be a possibility to add some file-based events in the future.

In the short-term, I'll try to look into what's happening on my end with the current refresh trigger.
In the long-term, it might be good to keep note of a possible need for these file-based events in case of a future issue

**Comment by craig-willis** [comment]
@bodom0015 The file/folder events were left for future work in https://github.com/whole-tale/girder_wholetale/pull/445 and there are no doubt others (versions, I think?).  I'll create a separate issue to track those.
